<?php
namespace App\Test\TestCase\Controller;

use App\Application;
use App\Controller\UsersController;
use App\Model\Table\UsersTable;
use Cake\ORM\TableRegistry;
use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;
use Cake\Utility\Security;
use Firebase\JWT\JWT;

/**
 * App\Controller\UsersController Test Case
 *
 * @uses \App\Controller\UsersController
 */
class UsersControllerTest extends TestCase
{
    use IntegrationTestTrait;
    /**
     * @var UsersTable
     */
    private $Users;

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [
        'app.Users'
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->Users = TableRegistry::getTableLocator()->get('Users');
    }

    /**
     * Test token method
     *
     * @return void
     */
    public function testToken()
    {
        $credentials = [
            'username' => 'marcos.adantas@hotmail.com',
            'password' => 'marcos2001'
        ];

        $this->post('/token', $credentials);

        $this->assertResponseOk();
    }

    /**
     * Test ping method
     *
     * @return void
     */
    public function testPing()
    {
        $token = $this->getToken();

        $this->configRequest([
            'headers' => ['Authorization' => 'Bearer ' . $token]
        ]);
        $this->get('/ping');
        $this->assertResponseOk();

    }

    public function getToken()
    {
        $entity = $this->Users->find()
            ->firstOrFail();

        $expireTime = time() + HOUR;
        $tokenJwt = JWT::encode([
            'sub' => $entity->getIdentifier(),
            'exp' => $expireTime
        ],Security::getSalt());

        return $tokenJwt;
    }
}
